name: Deploy Amplify with Terraform

on:
  workflow_dispatch:
    inputs:
      env:
        description: "Environment to Deploy"
        default: sandbox
        required: true
        type: choice
        options:
          - sandbox
          - dev
          - qastg
          - prod
  # push:
  #   branches:
  #     - main

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Detect changes
        id: changed-files
        uses: tj-actions/changed-files@v46.0.5
        with:
          files: |
            terraform/**
            terraform/**/*

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2

      - name: Configure AWS Credentials (OIDC)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::226727481186:role/essaypop-role
          aws-region: us-west-2
      - name: Sanity Check
        run: aws sts get-caller-identity # or your 'aws amplify' commands

      - name: Terraform Plan
        env:
          TF_VAR_github_owner: ${{ github.repository_owner }}
          TF_VAR_github_repo: ${{ github.event.repository.name }}
        if: (steps.changed-files.outputs.any_changed == 'true')
        run: |
          cd terraform && \
          terraform workspace select ${{ github.event.inputs.env }} || terraform workspace new ${{ github.event.inputs.env }} && \
          terraform init && \
          terraform plan && \
          terraform apply -auto-approve
